### PR TITLE
[ISSUE#13449] Fix service pagination

### LINKED ISSUE #13449: NACOS 3.0.0 服务列表分页存在问题
CatalogServiceV2Impl # listService的循环目标集合是否应该改成page.getPageItems()

### PR DESCRIPTION
**Pull request by OmCheeLin**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #13449
fix service pagination in `CatalogServiceV2Impl.java` and add test.

## Brief changelog

fix service pagination in `CatalogServiceV2Impl.java` and add revelant test.

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by OmCheeLin** [comment]
> @OmCheeLin Please sign cla first

ok, I have done it.

File: naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java [hunk 1]
```diff
@@ -55,18 +55,18 @@
  */
 @Component()
 public class CatalogServiceV2Impl implements CatalogService {
-    
+
```
Comment (KomachiSion) [inline naming/src/main/java/com/alibaba/nacos/naming/core/CatalogServiceV2Impl.java]: Please dont change the indent

**Review by KomachiSion — CHANGES_REQUESTED** [review]

**Comment by KomachiSion** [comment]
The only problem is the indent changed, please setting the indent and reformat these two files.

**Comment by wuyfee** [comment]
$\color{red}{FAILURE}$
[DETAILS](https://github.com/alibaba/nacos/actions/runs/15433146115)
 ✅ - docker:   success 
 ❌ - deploy (standalone & cluster & standalone_auth):   failure 
 ❌ - e2e-java-test (standalone & cluster & standalone_auth):   skipped 
 ❌ - e2e-go-test (standalone & cluster):   skipped 
 ❌ - e2e-cpp-test (standalone & cluster):   skipped 
 ❌ - e2e-csharp-test (standalone & cluster):   skipped 
 ❌ - e2e-nodejs-test (standalone & cluster):   skipped 
 ❌ - e2e-python-test (standalone & cluster):   skipped 
 ✅ - clean (standalone & cluster & standalone_auth):   success

**Comment by KomachiSion** [comment]
> The only problem is the indent changed, please setting the indent and reformat these two files.

@OmCheeLin Hello, please fix the indent. If still no response, PR will be closed.

**Comment by OmCheeLin** [comment]
> > The only problem is the indent changed, please setting the indent and reformat these two files.
> 
> @OmCheeLin Hello, please fix the indent. If still no response, PR will be closed.

ok，I will repair today

**Comment by OmCheeLin** [comment]
@KomachiSion I have repaired it.

**Review by KomachiSion — APPROVED** [review]

**Comment by OmCheeLin** [comment]
@KomachiSion Is this an unstable test?

**Comment by KomachiSion** [comment]
> @KomachiSion Is this an unstable test?

Please sync develop branch and retry, ut problem has fixed.

**Comment by OmCheeLin** [comment]
> > @KomachiSion Is this an unstable test?
> 
> Please sync develop branch and retry, ut problem has fixed.

done

**Review by KomachiSion — APPROVED** [review]
