### PR TITLE
[ISSUE#6272] Refactor Instance builder to build and handler request from http.

### LINKED ISSUE #6272: Refactor parse instance in InstanceController
Now, Nacos parses instance in InstanceController for v1 openAPI still use `com.alibaba.nacos.naming.core.Instance` which extends from `com.alibaba.nacos.api.naming.pojo.Instance`.

We hope in controller, the instance is the basic instance `com.alibaba.nacos.api.naming.pojo.Instance`. And In `InstanceOperatorServiceImpl` which contain v1 context to handle `com.alibaba.nacos.api.naming.pojo.Instance` to `com.alibaba.nacos.naming.core.Instance`.

```
private Instance parseInstance(HttpServletRequest request) throws Exception {
        
        String serviceName = WebUtils.required(request, CommonParams.SERVICE_NAME);
        String app = WebUtils.optional(request, "app", "DEFAULT");
        Instance instance = getIpAddress(request);
        // only in com.alibaba.nacos.api.naming.pojo.Instance. And will be lack in v2
        instance.setApp(app);
        instance.setServiceName(serviceName);
        // Generate simple instance id first. This value would be updated according to
        // INSTANCE_ID_GENERATOR.
        instance.setInstanceId(instance.generateInstanceId());
        instance.setLastBeat(System.currentTimeMillis());
        String metadata = WebUtils.optional(request, "metadata", StringUtils.EMPTY);
        if (StringUtils.isNotEmpty(metadata)) {
            instance.setMetadata(UtilsAndCommons.parseMetadata(metadata));
        }
        
        instance.validate();
        
        return instance;
    }
```

### PR DESCRIPTION
**Pull request by KomachiSion**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fix #6272 .

## Brief changelog

- Add InstanceBuilder and IdGenerator
- Add new builder for http request and client beat
- Use new builder to build api instance.

## Verifying this change

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/AppExtensionHandler.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+/**
+ * Instance extension handler for app field.
+ *
+ * @author xiweng.yy
+ */
+public class AppExtensionHandler implements InstanceExtensionHandler {
+    
+    private static final String APP_FIELD = "app";
+    
+    private static final String DEFAULT_APP = "DEFAULT";
```
Comment (pixystone) [inline naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/AppExtensionHandler.java:34]: Default value can be empty to reduce meta size.

Comment (KomachiSion) [reply naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/AppExtensionHandler.java:34]: The old logic use `DEFAULT`, so my refactor is just keep the default value.

```
private Instance parseInstance(HttpServletRequest request) throws Exception {

        String serviceName = WebUtils.required(request, CommonParams.SERVICE_NAME);
        String app = WebUtils.optional(request, "app", "DEFAULT");
       ....
```

File: naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilder.java [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+        return this;
+    }
+    
+    private void setAttributesToBuilder(RsInfo beatInfo) {
+        actualBuilder.setPort(beatInfo.getPort());
+        actualBuilder.setIp(beatInfo.getIp());
+        actualBuilder.setWeight(beatInfo.getWeight());
+        actualBuilder.setMetadata(beatInfo.getMetadata());
+        actualBuilder.setClusterName(beatInfo.getCluster());
+        actualBuilder.setServiceName(beatInfo.getServiceName());
```
Comment (pixystone) [inline naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/BeatInfoInstanceBuilder.java:79]: `beatInfo` may not have service name set before.

File: naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java [hunk 3]
```diff
@@ -371,4 +356,18 @@ public long getHeartBeatInterval(String namespaceId, String serviceName, String
         };
         return serviceManager.batchOperate(namespace, instanceOperationInfo, operateFunction);
     }
+    
+    private com.alibaba.nacos.naming.core.Instance parseInstance(Instance apiInstance) {
+        com.alibaba.nacos.naming.core.Instance result = new com.alibaba.nacos.naming.core.Instance();
```
Comment (pixystone) [inline naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java:361]: Can use `InstanceUpgradeHelper` instead.

File: naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java [hunk 4]
```diff
@@ -145,9 +145,6 @@ public void patchInstance(String namespaceId, String serviceName, InstancePatchO
         if (null != patchObject.getHealthy()) {
             instance.setHealthy(patchObject.getHealthy());
         }
-        if (null != patchObject.getApp()) {
```
Comment (pixystone) [inline naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java:148]: Why?

File: naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilder.java [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+    
+    private final SwitchDomain switchDomain;
+    
+    private HttpRequestInstanceBuilder(SwitchDomain switchDomain) {
+        this.actualBuilder = InstanceBuilder.newBuilder();
+        this.handlers = NacosServiceLoader.newServiceInstances(InstanceExtensionHandler.class);
+        this.switchDomain = switchDomain;
+    }
+    
+    public static HttpRequestInstanceBuilder newBuilder(SwitchDomain switchDomain) {
```
Comment (pixystone) [inline naming/src/main/java/com/alibaba/nacos/naming/pojo/instance/HttpRequestInstanceBuilder.java:62]: Can specify `DefaultInstanceEphemeral` value instead of switchDomain

File: naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java (hunk 4 above)
Comment (KomachiSion) [reply naming/src/main/java/com/alibaba/nacos/naming/core/InstanceOperatorServiceImpl.java:148]: This is a duplicate logic.

same logic in line 139 and 148. So remove 148
```
        if (null != patchObject.getApp()) {
            instance.setApp(patchObject.getApp());
        }
```

**Review by pixystone — APPROVED** [review]

**Review by realJackSun — APPROVED** [review]
