### PR TITLE
[ISSUE#12235]Fix the incorrect logging format in the ResponseExceptionHand…

### LINKED ISSUE #12235: In the ResponseExceptionHandler of the naming module, the wrong logging format was used.
**Describe the bug**
In the ResponseExceptionHandler of the naming module, the wrong logging format was used.

```
Loggers.SRV_LOG.error("got exception. {}", e.getErrMsg(), ExceptionUtil.getAllExceptionMsg(e));
```

### PR DESCRIPTION
**Pull request by HMYDK**
…ler of the naming module.

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #12235
Fix the incorrect logging format in the ResponseExceptionHandler of the naming module.

### CODE REVIEW

File: naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java [hunk 1]
```diff
@@ -54,10 +54,10 @@ public ResponseEntity<String> handleNacosException(NacosException e) {
      */
     @ExceptionHandler(NacosRuntimeException.class)
     public ResponseEntity<String> handleNacosRuntimeException(NacosRuntimeException e) {
-        Loggers.SRV_LOG.error("got exception. {}", e.getMessage(), ExceptionUtil.getAllExceptionMsg(e));
+        Loggers.SRV_LOG.error("got exception. {}", ExceptionUtil.getAllExceptionMsg(e));
         return ResponseEntity.status(e.getErrCode()).body(e.getMessage());
     }
-
```
Comment (KomachiSion) [inline naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java:60]: Please don't change the indents.

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java (hunk 1 above)
Comment (HMYDK) [reply naming/src/main/java/com/alibaba/nacos/naming/exception/ResponseExceptionHandler.java:60]: 我是用项目中的`nacos-code-style-for-idea.xml`重新格式化了代码。

**Review by KomachiSion — APPROVED** [review]
