### PR TITLE
[1.x] set max days of Tomcat access log

### LINKED ISSUE #7446: 设置server.tomcat.accesslog.max-days日志保存天数不生效
**Describe the bug**
设置server.tomcat.accesslog.max-days参数不生效，看了一下代码，无论是1.4.2还是2.0.3引用的springboot都是2.1.17.RELEASE，这个版本的TomcatWebServerAccessLogCustomizer没有调用tomcat的setMaxDays方法，所以设置上述参数不生效。
springboot 2.2.0.RELEASE以上版本有调用，但是2.2.0和2.1.17之间的差异有点多，是否兼容还有待测试。

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #7446

### CODE REVIEW

File: console/src/main/java/com/alibaba/nacos/console/config/TomcatWebServerAccessLogCustomizer.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+
+/**
+ * Set max days of tomcat access log
+ * as TomcatWebServerFactoryCustomizer of springboot 2.1.17.RELEASE which Nacos is currently using does not set it.
+ *
+ * @author zrlw
+ */
+@Component
+public class TomcatWebServerAccessLogCustomizer implements WebServerFactoryCustomizer<TomcatServletWebServerFactory> {
+    @Value("${server.tomcat.accesslog.max-days:-1}")
```
Comment (realJackSun) [inline console/src/main/java/com/alibaba/nacos/console/config/TomcatWebServerAccessLogCustomizer.java:36]: 建议在application.properties也加上这个属性。

**Review by realJackSun — CHANGES_REQUESTED** [review]

**Review by realJackSun — APPROVED** [review]
