### PR TITLE
[ISSUE #10598] Fix nacos-client get the wrong index of the nacos server list when use nacos-address endpoint

### LINKED ISSUE #10598: when nacos client used nacos address as config value, there is a bug at choose nacos server methd which used a fixed index value when get the nacos server list
**Describe the bug**
when nacos client used nacos address as config value, there is a bug at choose nacos server methd which used a fixed index value when get the nacos server address array

当 nacos 客户端使用地址服务器作为配置时，在通过nacos地址服务器拿到 nacos server 列表后，取的一个固定下标获取 server 地址，导致当有多个客户端请求，请求没有被平均分散到各个 server

**Expected behavior**
different nacos client request  should go to different nacos server

多个客户端请求应该是均分到各个 nacos server 地址

**Actually behavior**
different nacos client connect request  should go to the same nacos server

多个客户端请求跑到同一个 nacos server 地址

**How to Reproduce**
com.alibaba.nacos.client.naming.core.ServerListManager#currentIndex
is initialized a **random** value only when !serverList.isEmpty()
```java
   public ServerListManager(NacosClientProperties properties, String namespace) {
        this.namespace = namespace;
        initServerAddr(properties);
        if (!serverList.isEmpty()) {
            currentIndex.set(new Random().nextInt(serverList.size()));
        }
        if (serverList.isEmpty() && StringUtils.isEmpty(endpoint)) {
            throw new NacosLoadException("serverList is empty,please check configuration");
        }
    }
```
and is not considerate to the values at serversFromEndpoint

ServerListManager#currentIndex 下标值初始化为随机值的逻辑有问题，nacos 客户端如果使用 nacos address server (地址服务器) 作为配置，该下标值没有被初始化，而是一个固定值，导致所有的客户端都是用同一个 nacos server

pr 稍后提交

### PR DESCRIPTION
**Pull request by 1em0n9527**
## What is the purpose of the change
fix nacos client get the wrong index of nacos server list  when use nacos-address endpoint
fix #10598 
## Brief changelog
fix an index value which did not initialized

## Verifying this change
XXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Review by Daydreamer-ia — DISMISSED** [review]

File: client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java [hunk 1]
```diff
@@ -86,11 +86,10 @@ public ServerListManager(Properties properties) {
     public ServerListManager(NacosClientProperties properties, String namespace) {
         this.namespace = namespace;
         initServerAddr(properties);
-        if (!serverList.isEmpty()) {
-            currentIndex.set(new Random().nextInt(serverList.size()));
-        }
-        if (serverList.isEmpty() && StringUtils.isEmpty(endpoint)) {
+        if (getServerList().isEmpty()) {
```
Comment (KomachiSion) [inline client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java:89]: 判断条件需要改一下, 需要判断endpoint是否为空

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java (hunk 1 above)
Comment (KomachiSion) [reply client/src/main/java/com/alibaba/nacos/client/naming/core/ServerListManager.java:89]: serversFromEndpoint 如果 地址服务器异常或者网络异常， 这里判空可能会抛出异常，这里应该异常的情况是endpoint未配置且serverlist为空。即保持原有的判断。

**Review by KomachiSion — APPROVED** [review]
