### PR TITLE
repair the NPE and Optimize related code

### LINKED ISSUE #1698: Nullpointer exception if sync content is empty
image

### PR DESCRIPTION
**Pull request by pbting**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #1698 #1609 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [X] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [X] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [X] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: naming/src/main/java/com/alibaba/nacos/naming/boot/RunningConfig.java [hunk 1]
```diff
@@ -54,8 +58,13 @@ public static int getServerPort() {
 
     public static String getContextPath() {
 
-        if (StringUtils.isBlank(contextPath)) {
-            return UtilsAndCommons.NACOS_SERVER_CONTEXT;
+        if (!isServerInitialized) {
+            String contextPath = PropertyUtil.getProperty(Constants.WEN_CONTEXT_PATH);
```
Comment (nkorange) [inline naming/src/main/java/com/alibaba/nacos/naming/boot/RunningConfig.java]: spell error
