### PR TITLE
[ISSUE #13143] client support both v1 and v3 login url.

### LINKED ISSUE #13143: [Nacos 3.0] client鉴权失败问题
**Describe the bug**

打开server API的鉴权配置
Image

client日志报错，显示登录接口资源不存在
Image

在server API的启动类中，ComponentScan是把auth plugin的包排除掉了，这样不会扫描鉴权相关的controller，是不是有点问题
Image

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

### PR DESCRIPTION
**Pull request by misakacoder**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #13143

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java [hunk 1]
```diff
@@ -82,6 +84,11 @@ public LoginIdentityContext getResponse(Properties properties) {
         try {
             HttpRestResult<String> restResult = nacosRestTemplate.postForm(url, Header.EMPTY,
                     Query.newInstance().initParams(params), bodyMap, String.class);
+            if (restResult.getCode() == 404) {
```
Comment (KomachiSion) [inline client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java:87]: 501也要判断， api不存在时， 501代码也是可能的

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java (hunk 1 above)
Comment (misakacoder) [reply client-basic/src/main/java/com/alibaba/nacos/client/auth/impl/process/HttpLoginProcessor.java]: 已修改

**Review by KomachiSion — APPROVED** [review]
