### PR TITLE
fix issues #1840

### LINKED ISSUE #1840: Error creating cache directory at startup time [starting the time register to create a cache directory error]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Error creating cache directory at startup time
启动时报建立缓存目录错误

### Describe what you expected to happen
Occasionally reporting cache creation errors at startup,The error message is as follows:
启动时偶发性报建立缓存错误,错误信息如下：

java.lang.IllegalStateException: failed to create cache dir: /root/nacos/naming/public

	at com.alibaba.nacos.client.naming.cache.DiskCache.makeSureCacheDirExists(DiskCache.java:155) ~[nacos-client-1.0.0.jar!/:na]

	at com.alibaba.nacos.client.naming.cache.DiskCache.write(DiskCache.java:45) ~[nacos-client-1.0.0.jar!/:na]

### How to reproduce it (as minimally and precisely as possible)

启动

### Tell us your environment
centos 7、java8

### Anything else we need to know?

com.alibaba.nacos.client.naming.cache.DiskCache类里面
第49行第50行的注释做了多实例冲突的优化处理，然而第153行同样的场景却未做同样的优化处理。
Inside the com.alibaba.nacos.client.naming.cache.DiskCache class
The comment in line 49, line 50, optimizes multi-instance conflicts, but the same scenario in line 153 does not.

### PR DESCRIPTION
**Pull request by stackisok**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #1840

Avoiding conflicted for creating directory.

## Brief changelog

Using lock and double check.Avoiding conflicted among multiple threads and making sure the efficiency.The third "!cacheDir.exists()" can avoid conflicted among jvms.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: client/src/main/java/com/alibaba/nacos/client/naming/cache/DiskCache.java [hunk 1]
```diff
@@ -150,8 +155,20 @@ public static String getLineSeparator() {
 
     private static File makeSureCacheDirExists(String dir) {
         File cacheDir = new File(dir);
-        if (!cacheDir.exists() && !cacheDir.mkdirs()) {
-            throw new IllegalStateException("failed to create cache dir: " + dir);
+        //Reducing the cost of taking lock
+        if (!cacheDir.exists()) {
+            try {
+                DIR_MK_LOCK.tryLock(1000, TimeUnit.MILLISECONDS);
```
Comment (chuntaojun) [inline client/src/main/java/com/alibaba/nacos/client/naming/cache/DiskCache.java]: Suggestions on the outside the try block

**Comment by stackisok** [comment]
I suppose i complex the problem at first.Thanks @chuntaojun
