### PR TITLE
[ISSUE #8925] fix that the replaceAll operation is invalid

### LINKED ISSUE #8925: [Bug] the value of `hasQueryString` is aways false in the ServerListManager
image

### LINKED ISSUE #8928: [Bug] the replaceAll  operation of `serverName` is invalid in the ServerListManager
image

### PR DESCRIPTION
**Pull request by onewe**
Close #8928

Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

XXXXX

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

**Comment by Klohkovandrei1986** [comment]
Het

**Review by Klohkovandrei1986 — APPROVED** [review]

File: client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java [hunk 1]
```diff
@@ -223,24 +223,24 @@ public ServerListManager(Properties properties) throws NacosException {
...
+        String serverName;
         //1.user define server name.
         if (properties != null && properties.containsKey(PropertyKeyConst.SERVER_NAME)) {
             serverName = properties.get(PropertyKeyConst.SERVER_NAME).toString();
         } else {
             // if fix url,use fix url join string.
             if (isFixed) {
                 serverName = FIXED_NAME + "-" + (StringUtils.isNotBlank(namespace) ? (StringUtils.trim(namespace) + "-")
-                        : "") + getFixedNameSuffix(serverUrls.toArray(new String[serverUrls.size()]));
+                        : "") + getFixedNameSuffix(serverUrls.toArray(new String[0]));
```
Comment (KomachiSion) [inline client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java:234]: why 0 length?

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java (hunk 1 above)
Comment (onewe) [reply client/src/main/java/com/alibaba/nacos/client/config/impl/ServerListManager.java:234]: Don't need to specify the array length if the ArrayList.length equal the Array.length. see JDK api List.toArray()

**Review by KomachiSion — APPROVED** [review]
