### PR TITLE
[ISSUE #8709] check serverList size before reconnect to server

### LINKED ISSUE #8709: Arithmetic exception occurred when server list is empty
Arithmetic exception occurred when reconnect to server while server list is empty;
besides, improve some code in client module.

### PR DESCRIPTION
**Pull request by MajorHe1**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #8709 

## Brief changelog

XX

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java [hunk 1]
```diff
@@ -551,6 +551,10 @@ protected void reconnect(final ServerInfo recommendServerInfo, boolean onRequest
                     recommendServer.set(null);
                 }
                 
+                if (RpcClient.this.serverListFactory.getServerList().size() == 0) {
```
Comment (Oliverwqcwrw) [inline common/src/main/java/com/alibaba/nacos/common/remote/client/RpcClient.java:554]:
```suggestion
                if (CollectionUtils.isEmpty(RpcClient.this.serverListFactory.getServerList())) {
```

**Review by Oliverwqcwrw — CHANGES_REQUESTED** [review]

**Review by Oliverwqcwrw — APPROVED** [review]

**Review by KomachiSion — APPROVED** [review]
