### PR TITLE
[ISSUE #5517],invoke reQuery after change queryType

### LINKED ISSUE #5517: DataId and  Group lost  in Ip query option mode
**Describe the bug**
the Ip query option mode the DataId and  Group lost  when we swith the option 配置 to IP 
配置选项结果：
 
image

切换为IP结果：
image

**Expected behavior**
donot show the data or complete the Group and DataId

**Acutally behavior**
the Group and DataId lost in IP query option.

**How to Reproduce**
1. Go to '监听查询'
2. Click on '查询维度，切换为IP'
3. See the data table.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [the lasted]
 - Module [console]

**Additional context**
no

### PR DESCRIPTION
**Pull request by drgnchan**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

fix #5517 ,listening on change, and again query after the change of  query type.

## Brief changelog

add onChange func in Select Of ListeningToQuery.js

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js [hunk 1]
```diff
@@ -203,6 +203,10 @@ class ListeningToQuery extends React.Component {
                     dataSource={selectDataSource}
                     style={{ width: 200 }}
                     {...this.init('type')}
+                    onChange={(value) => {
```
Comment (brothelul) [inline console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js:206]: 可能把onChange后面的这个段代码抽成一个方法，后续会好维护些。

Comment (drgnchan) [reply console-ui/src/pages/ConfigurationManagement/ListeningToQuery/ListeningToQuery.js:206]: 感觉这个onChange在其他地方用不到，只适用于此处的select，所以就没想着封装

**Comment by KomachiSion** [comment]
Preparing release 1.4.2 and pending PR temparately.

**Review by KomachiSion — APPROVED** [review]
