### PR TITLE
Fix#3973

### LINKED ISSUE #3973: 第一次运行时,导入数据找不到namespace
**Describe the bug**
第一次运行,没有任何配制数据时,向public命名空间导入数据,提示找不到 namespace

### PR DESCRIPTION
**Pull request by KeRan213539**
Fix #3973

### CODE REVIEW

File: config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java [hunk 1]
```diff
@@ -690,11 +691,19 @@ public GroupkeyListenserStatus getListeners(@RequestParam("dataId") String dataI
         return ResultBuilder.buildSuccessResult("Clone Completed Successfully", saveResult);
     }
     
+    /**
+     * Treat the tenant parameters with values of "public" and "null" as an empty string.
+     * @author klw(213539@qq.com)
```
Comment (KomachiSion) [inline config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java:696]: method do not need author

File: config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java [hunk 2]
```diff
@@ -690,11 +691,19 @@ public GroupkeyListenserStatus getListeners(@RequestParam("dataId") String dataI
...
+     * 2020/10/12 15:59
+     * @param tenant tenant
+     * @return java.lang.String
```
Comment (KomachiSion) [inline config/src/main/java/com/alibaba/nacos/config/server/controller/ConfigController.java:699]: return annotation should describe what content method return, only type is not useful

**Review by KomachiSion — CHANGES_REQUESTED** [review]

**Review by KomachiSion — APPROVED** [review]

**Review by chuntaojun — APPROVED** [review]

**Review by chuntaojun — APPROVED** [review]

**Review by KomachiSion — APPROVED** [review]
