### PR TITLE
[ISSUE #10318]fix import bug

### LINKED ISSUE #10318: web控制台点击导入配置无任何反应
**Describe the bug**
web控制台点击导入配置无任何反应

**Expected behavior**
弹出窗口选择文件导入配置

**Actually behavior**
无任何反应，并且 console 打印 "SyntaxError: "undefined" is not valid JSON" 和 "caught ReferenceError: goLogin is not defined"

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version 2.2.2

### PR DESCRIPTION
**Pull request by 985492783**
fix import frontend bug fix #10318 
@KomachiSion

### CODE REVIEW

File: console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js [hunk 1]
```diff
@@ -1009,16 +1009,28 @@ class ConfigurationManagement extends React.Component {
     }
   }
 
+  goLogin() {
```
Comment (KomachiSion) [inline console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js:1012]: Why change the goLogin implementation?

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js (hunk 1 above)
Comment (985492783) [reply console-ui/src/pages/ConfigurationManagement/ConfigurationManagement/ConfigurationManagement.js:1012]: method goLogin miss references，i just make a copy from other js-file.

**Review by KomachiSion — APPROVED** [review]

**Comment by wilsonwu** [comment]
Does 2.2.3 with this fix?
