### PR TITLE
[ISSUE #6535] throw the NacosException in 2.x to keep same with 1.x when Service doesn't exist.

### LINKED ISSUE #6535: Inconsistent results returned by different versions of the open-api `/nacos/v1/ns/service`
**Describe the bug**
In version 1.4.x，GET `/nacos/v1/ns/service`  querying a not exist service , return status code `500`.  return message body `caused: service api@@hyperf is not found!`

But in version 2.0.x ，return status code `200` ， return message body `{"namespaceId":"67f9ce9b-c3d5-4dbb-acf8-308b6b0b928e","groupName":"api","name":"hyperf","protectThreshold":0.0,"metadata":{},"selector":{"type":"none"},"clusters":[]}`

why？

### PR DESCRIPTION
**Pull request by brotherlu-xcq**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fixes #6535 

## Brief changelog

throw the service not find exception in Nacos 2.x when service does not exist.

## Verifying this change

image

Follow this checklist to help us incorporate your contribution quickly and easily:

* [ ] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [ ] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [ ] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java [hunk 1]
```diff
@@ -91,8 +91,13 @@ public void delete(String namespaceId, String serviceName) throws NacosException
     
     @Override
     public ObjectNode queryService(String namespaceId, String serviceName) throws NacosException {
-        ObjectNode result = JacksonUtils.createEmptyJsonNode();
         Service service = getServiceFromGroupedServiceName(namespaceId, serviceName, true);
+        boolean serviceExist = ServiceManager.getInstance().containSingleton(service);
+        if (!serviceExist) {
```
Comment (KomachiSion) [inline naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java:96]: merge `serviceExist`, because `serviceExist` will not be used after this logic.

**Review by KomachiSion — CHANGES_REQUESTED** [review]

File: naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java (hunk 1 above)
Comment (brotherlu-xcq) [reply naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java:96]: OK, I will merge it.

Comment (abood640) [reply naming/src/main/java/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.java]: > merge `serviceExist`, because `serviceExist` will not be used after this logic.

**Review by KomachiSion — APPROVED** [review]
