### PR TITLE
fix not support java 1.7

### LINKED ISSUE #736: nacos-client0.8.0 not support jdk1.7, compile error
nacos-client0.8.0 not support jdk1.7, compile error;

java.lang.UnsupportedClassVersionError: io/micrometer/core/instrument/ImmutableTag : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_03]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791) ~[na:1.7.0_03]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_03]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_03]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_03]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_03]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_03]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_03]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_03]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[na:1.7.0_03]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_03]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[na:1.7.0_03]
	at com.alibaba.nacos.client.monitor.MetricsMonitor.<clinit>(MetricsMonitor.java:39) ~[nacos-client-0.8.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:57) ~[nacos-client-0.8.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:212) ~[nacos-client-0.8.0.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:135) ~[nacos-client-0.8.0.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:91) ~[nacos-client-0.8.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:83) ~[spring-cloud-alibaba-nacos-config-0.1.2.BUILD-SNAPSHOT.jar:0.1.2.BUILD-SNAPSHOT]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:70) ~[spring-cloud-alibaba-nacos-config-0.1.2.BUILD-SNAPSHOT.jar:0.1.2.BUILD-SNAPSHOT]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:183) ~[spring-cloud-alibaba-nacos-config-0.1.2.BUILD-SNAPSHOT.jar:0.1.2.BUILD-SNAPSHOT]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadExtConfiguration(NacosPropertySourceLocator.java:136) ~[spring-cloud-alibaba-nacos-config-0.1.2.BUILD-SNAPSHOT.jar:0.1.2.BUILD-SNAPSHOT]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:94) ~[spring-cloud-alibaba-nacos-config-0.1.2.BUILD-SNAPSHOT.jar:0.1.2.BUILD-SNAPSHOT]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) ~[spring-cloud-context-1.3.1.RELEASE.jar:1.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:567) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:338) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:301) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.sctel.Application.main(Application.java:17) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_03]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_03]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_03]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_03]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.9.RELEASE.jar:1.5.9.RELEASE]

### PR DESCRIPTION
**Pull request by TsingLiang**
Please do not create a Pull Request without creating an issue first.

## What is the purpose of the change

Fix #736

## Brief changelog

Fix #736

Follow this checklist to help us incorporate your contribution quickly and easily:

* [x] Make sure there is a Github issue filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
* [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
* [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
* [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/alibaba/nacos/tree/master/test).
* [x] Run `mvn -B clean package apache-rat:check findbugs:findbugs -Dmaven.test.skip=true` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.

### CODE REVIEW

File: client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java [hunk 1]
```diff
@@ -42,57 +42,54 @@ public void start() throws NacosException {
...
-        long start = System.currentTimeMillis();
-        long end = 0;
+        Histogram.Timer timer = MetricsMonitor.getConfigRequestMonitor("GET", path, "NA");
         HttpResult result = null;
         try {
             result = httpAgent.httpGet(path, headers, paramValues, encoding, readTimeoutMs);
         } catch (IOException e) {
-            end = System.currentTimeMillis();
-            MetricsMonitor.getConfigRequestMonitor("GET", path, "NA").record(end - start, TimeUnit.MILLISECONDS);
+            timer.observeDuration();
```
Comment (hxy1991) [inline client/src/main/java/com/alibaba/nacos/client/config/http/MetricsHttpAgent.java]: Lines 50-51 and 55-56 can be placed on the "finally block", similar below.

File: client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java [hunk 2]
```diff
@@ -15,67 +15,42 @@
...
-    private static AtomicInteger dom2BeatSize = new AtomicInteger();
-    private static AtomicInteger listenConfigCount = new AtomicInteger();
-
-    static {
-        List<Tag> tags = new ArrayList<Tag>();
-        tags.add(new ImmutableTag("module", "naming"));
-        tags.add(new ImmutableTag("name", "subServiceCount"));
-        Metrics.gauge("nacos_monitor", tags, serviceInfoMapSize);
+    private static Gauge nacosMonitor = Gauge.build()
+        .name("nacos_monitor").labelNames("module", "name")
```
Comment (hxy1991) [inline client/src/main/java/com/alibaba/nacos/client/monitor/MetricsMonitor.java]: The value of module is "name" or "naming"
