### PR TITLE
[ISSUE #7869 #7750]fix bug in permissions management module,  such as redundant 'nacos,' when change password

### LINKED ISSUE #7869: win10 standalone模式，控制台添加用户，用户名总是多了nacos,
如题，win10 standalone模式打开，在控制台上添加用户，u=test,p=test,添加完毕后，显示添加的用户名为nacos,test，这就导致了既不能登录，也不能修改和删除这个账号。版本，最新的1.4.3和2.0.4二进制版本都一样的bug，一切都没改过，登录的账号都是默认的nacos/nacos

### PR DESCRIPTION
**Pull request by jefferson-chern**
Please do not create a Pull Request without creating an issue first.
fix and close #7869 and #7750

## What is the purpose of the change
there are no redundant 'nacos,' string when change password, add user and so on.

## Brief changelog
delete `username` param when request from console to backend, because the user info saved in session, see PR #7804.

## Verifying this change

* clear cookie in your browser;
* change the password of nacos, or add user.
image

### CODE REVIEW

**Review by chuntaojun — APPROVED** [review]

**Review by KomachiSion — APPROVED** [review]

**Review by KomachiSion — CHANGES_REQUESTED** [review]
see #6014, const may be not need remove

**Comment by jefferson-chern** [comment]
> see #6014, const may be not need remove

but i think remove the useless variables `username` is better, make the code more simply.

File: console/src/main/java/com/alibaba/nacos/console/controller/UserController.java [hunk 1]
```diff
@@ -161,11 +161,11 @@ private boolean hasPermission(String username, HttpServletRequest request) {
         if (!authConfigs.isAuthEnabled()) {
             return true;
         }
-        if (Objects.isNull(request.getAttribute(RequestUtil.NACOS_USER_KEY))) {
+        if (Objects.isNull(request.getSession().getAttribute(RequestUtil.NACOS_USER_KEY))) {
```
Comment (jefferson-chern) [inline console/src/main/java/com/alibaba/nacos/console/controller/UserController.java:164]: this commit is that when the authentication switch is turned on, there is no way to change the password(forbidden), because the user information has been saved in the session, but the previous code was obtained directly from reqeust.

**Comment by jefferson-chern** [comment]
> see #6014, const may be not need remove

done

**Review by KomachiSion — APPROVED** [review]

**Comment by fengyonghui** [comment]
where to find this build?
