### PR TITLE
Fix the Chinese description in announcement under English console

### LINKED ISSUE #11706: Console通知面板在英文界面仍然显示中文
如下图所示：

image

### PR DESCRIPTION
**Pull request by lcmarvin**
Try to fix #11706

### CODE REVIEW

File: console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java [hunk 1]
```diff
@@ -62,8 +63,9 @@ public ResponseEntity<Map<String, String>> serverState() {
     }
     
     @GetMapping("/announcement")
-    public RestResult<String> getAnnouncement() {
-        File announcementFile = new File(EnvUtil.getConfPath(), ANNOUNCEMENT_FILE);
+    public RestResult<String> getAnnouncement(@RequestParam("language") String language) {
```
Comment (KomachiSion) [inline console/src/main/java/com/alibaba/nacos/console/controller/ServerStateController.java:66]: language should required=false and default as zh-CN to adapt old logic

**Review by KomachiSion — CHANGES_REQUESTED** [review]

**Review by KomachiSion — APPROVED** [review]
